import type { Metadata } from 'next';
import Link from 'next/link';

export const metadata: Metadata = {
  title: 'Terms of Service — BizPlan Genius',
  description: 'Terms of Service for BizPlan Genius business plan generator.',
};

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-white">
      {/* Header */}
      <header className="border-b border-gray-100">
        <div className="max-w-4xl mx-auto px-4 py-6 flex items-center justify-between">
          <Link href="/" className="text-xl font-bold text-gray-900 hover:text-gray-700 transition">
            BizPlan Genius
          </Link>
          <Link href="/" className="text-sm text-gray-500 hover:text-gray-700 transition">
            ← Back to Home
          </Link>
        </div>
      </header>

      {/* Content */}
      <main className="max-w-4xl mx-auto px-4 py-16">
        <h1 className="text-3xl font-bold text-gray-900 mb-2">Terms of Service</h1>
        <p className="text-sm text-gray-500 mb-12">Last updated: April 4, 2026</p>

        <div className="prose prose-gray max-w-none space-y-10 text-gray-700 leading-relaxed">

          {/* 1 */}
          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-3">1. Agreement to Terms</h2>
            <p>
              By accessing or using the BizPlan Genius website at bizplangenius.com (the &ldquo;Service&rdquo;),
              you agree to be bound by these Terms of Service (&ldquo;Terms&rdquo;). If you do not agree to these
              Terms, you must not use the Service. These Terms constitute a legally binding agreement between you
              and BizPlan Genius (&ldquo;we,&rdquo; &ldquo;us,&rdquo; or &ldquo;our&rdquo;).
            </p>
            <p className="mt-3">
              We reserve the right to modify these Terms at any time. Changes become effective upon posting to this
              page. Your continued use of the Service after changes are posted constitutes acceptance of the updated Terms.
            </p>
          </section>

          {/* 2 */}
          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-3">2. Description of Service</h2>
            <p>
              BizPlan Genius provides an artificial intelligence-powered business plan generation service. Users
              submit business information through our online form, make a one-time payment, and receive a generated
              business plan delivered as a downloadable PDF and on-screen web view. The business plans are generated
              using AI technology and publicly available market data.
            </p>
          </section>

          {/* 3 */}
          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-3">3. Important Disclaimers</h2>
            <p className="font-medium text-gray-900">
              Please read this section carefully. It contains important limitations on the nature of our Service.
            </p>
            <ul className="mt-3 space-y-3 list-disc pl-5">
              <li>
                <strong>Not Professional Advice.</strong> The business plans generated by our Service are for
                informational and planning purposes only. They do not constitute financial advice, investment advice,
                legal advice, tax advice, or any other form of professional counsel. You should consult qualified
                professionals (accountants, attorneys, financial advisors) before making business decisions.
              </li>
              <li>
                <strong>AI-Generated Content.</strong> Our business plans are generated using artificial intelligence.
                While we strive for accuracy, AI-generated content may contain errors, inaccuracies, outdated information,
                or omissions. You are solely responsible for reviewing, verifying, and validating all information contained
                in your business plan before relying on it or presenting it to any third party.
              </li>
              <li>
                <strong>No Guarantee of Outcomes.</strong> We make no guarantees, representations, or warranties that
                any business plan generated through our Service will result in business success, secure funding, obtain
                loan approval, attract investors, or achieve any particular outcome. Business success depends on many
                factors beyond the scope of a business plan.
              </li>
              <li>
                <strong>Market Data and Projections.</strong> Market data, competitor information, financial projections,
                and statistics included in generated business plans are based on AI analysis of available information at
                the time of generation. These figures are estimates and should not be treated as verified facts. Market
                conditions change rapidly, and data may become outdated. You are responsible for independently verifying
                all data, figures, and claims before relying on them.
              </li>
              <li>
                <strong>Third-Party Use.</strong> If you present a business plan generated by our Service to banks,
                investors, lenders, partners, or any other third party, you do so at your own risk and discretion.
                We are not responsible for how third parties interpret, evaluate, or act upon the contents of your
                business plan.
              </li>
            </ul>
          </section>

          {/* 4 */}
          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-3">4. Payment and Pricing</h2>
            <ul className="space-y-3 list-disc pl-5">
              <li>
                Our Service is offered as a one-time purchase at the price displayed on our website at the time of checkout.
              </li>
              <li>
                All payments are processed securely through Stripe, a third-party payment processor. We do not store
                your credit card information on our servers.
              </li>
              <li>
                Prices are listed in US Dollars (USD) and are subject to change without notice. Price changes do not
                affect orders already completed.
              </li>
              <li>
                All sales are final upon delivery of your business plan. By completing your purchase, you acknowledge
                that digital goods are delivered immediately and that the statutory right of withdrawal may not apply
                once delivery has occurred.
              </li>
            </ul>
          </section>

          {/* 5 */}
          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-3">5. Refund Policy</h2>
            <p>
              We offer a satisfaction guarantee. If you are not satisfied with the quality of your generated business
              plan, you may request a refund within 7 days of purchase by contacting us at{' '}
              <a href="mailto:support@bizplangenius.com" className="text-blue-600 hover:text-blue-800 underline">
                support@bizplangenius.com
              </a>. Refund requests are evaluated on a case-by-case basis.
            </p>
            <p className="mt-3">
              Refunds are not available if you have already used or distributed the business plan to third parties
              (banks, investors, partners, etc.), or if more than 7 days have passed since the date of purchase.
            </p>
          </section>

          {/* 6 */}
          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-3">6. Intellectual Property and Ownership</h2>
            <ul className="space-y-3 list-disc pl-5">
              <li>
                <strong>Your Business Plan.</strong> Upon payment, you receive a non-exclusive, perpetual license to
                use, modify, reproduce, and distribute the business plan generated for you for any lawful purpose,
                including presenting it to third parties.
              </li>
              <li>
                <strong>Your Input.</strong> You retain all rights to the business information, ideas, and data you
                submit through our form. We do not claim ownership of your input.
              </li>
              <li>
                <strong>Our Service.</strong> The BizPlan Genius brand, website, software, templates, formatting,
                design elements, and underlying technology remain our exclusive property and are protected by applicable
                intellectual property laws. You may not copy, reverse-engineer, or redistribute our Service, platform,
                or technology.
              </li>
              <li>
                <strong>No Exclusivity.</strong> Business plans are generated based on your unique inputs, but we do
                not guarantee that the content, structure, or recommendations will be entirely unique. Similar businesses
                may receive business plans with similar market data, competitor analyses, or strategic recommendations.
              </li>
            </ul>
          </section>

          {/* 7 */}
          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-3">7. User Responsibilities</h2>
            <p>By using our Service, you agree to:</p>
            <ul className="mt-3 space-y-3 list-disc pl-5">
              <li>Provide accurate, truthful, and complete information about your business when submitting the form.</li>
              <li>Review and verify all generated content before relying on it or presenting it to others.</li>
              <li>Use the Service and generated business plans only for lawful purposes.</li>
              <li>Not use our Service to generate plans for businesses that are illegal or engaged in fraudulent activity.</li>
              <li>Not attempt to access, disrupt, or interfere with our Service, servers, or systems.</li>
              <li>Not resell, redistribute, or commercially exploit our Service or platform without written permission.</li>
            </ul>
          </section>

          {/* 8 */}
          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-3">8. Data Handling and Privacy</h2>
            <p>
              Your use of our Service is also governed by our{' '}
              <Link href="/privacy" className="text-blue-600 hover:text-blue-800 underline">
                Privacy Policy
              </Link>, which describes how we collect, use, and protect your personal and business information.
            </p>
            <p className="mt-3">
              We use your submitted business information solely to generate your business plan. We may retain
              anonymized or aggregated data for the purpose of improving our Service. We do not sell your personal
              information to third parties.
            </p>
          </section>

          {/* 9 */}
          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-3">9. Service Availability</h2>
            <p>
              We strive to maintain uninterrupted access to our Service but do not guarantee that the Service will
              be available at all times. The Service may be temporarily unavailable due to maintenance, updates,
              server issues, or circumstances beyond our control. We are not liable for any loss or inconvenience
              caused by Service downtime.
            </p>
            <p className="mt-3">
              We reserve the right to modify, suspend, or discontinue any aspect of the Service at any time without
              prior notice. If we permanently discontinue the Service, we will fulfill any outstanding paid orders.
            </p>
          </section>

          {/* 10 */}
          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-3">10. Limitation of Liability</h2>
            <p>
              To the maximum extent permitted by applicable law, BizPlan Genius, its owners, operators, employees,
              agents, and affiliates shall not be liable for any indirect, incidental, special, consequential, or
              punitive damages, including but not limited to loss of profits, business opportunities, revenue, data,
              goodwill, or other intangible losses, arising out of or related to your use of (or inability to use)
              our Service.
            </p>
            <p className="mt-3">
              Our total aggregate liability for any claim arising out of or related to these Terms or the Service
              shall not exceed the amount you paid to us for the specific business plan that is the subject of the claim.
            </p>
            <p className="mt-3">
              Without limiting the foregoing, we are not liable for any decisions you make based on the content of a
              generated business plan, any actions taken by third parties (banks, investors, partners) based on your
              business plan, any financial losses resulting from business decisions informed by a generated plan, or
              any inaccuracies, errors, or omissions in AI-generated content.
            </p>
          </section>

          {/* 11 */}
          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-3">11. Disclaimer of Warranties</h2>
            <p>
              The Service is provided on an &ldquo;AS IS&rdquo; and &ldquo;AS AVAILABLE&rdquo; basis without
              warranties of any kind, whether express or implied, including but not limited to implied warranties
              of merchantability, fitness for a particular purpose, accuracy, completeness, and non-infringement.
            </p>
            <p className="mt-3">
              We do not warrant that the Service will meet your specific requirements, that generated business plans
              will be error-free or complete, that market data or competitor information will be accurate or current,
              that financial projections will reflect actual results, or that the Service will be uninterrupted or secure.
            </p>
          </section>

          {/* 12 */}
          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-3">12. Indemnification</h2>
            <p>
              You agree to indemnify, defend, and hold harmless BizPlan Genius, its owners, operators, employees,
              agents, and affiliates from and against any and all claims, liabilities, damages, losses, costs, and
              expenses (including reasonable attorneys&rsquo; fees) arising out of or related to your use of the
              Service, your violation of these Terms, your presentation of a generated business plan to any third
              party, any business decisions made based on generated content, or your violation of any applicable law
              or regulation.
            </p>
          </section>

          {/* 13 */}
          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-3">13. Third-Party Services</h2>
            <p>
              Our Service integrates with third-party services including Stripe (payment processing) and AI providers
              (content generation). These services are governed by their own terms and privacy policies. We are not
              responsible for the practices, availability, or content of any third-party services.
            </p>
          </section>

          {/* 14 */}
          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-3">14. Prohibited Uses</h2>
            <p>You may not use the Service to:</p>
            <ul className="mt-3 space-y-3 list-disc pl-5">
              <li>Generate business plans for illegal, fraudulent, or deceptive businesses.</li>
              <li>Misrepresent AI-generated content as professional advice to obtain loans or investments under false pretenses.</li>
              <li>Infringe upon the intellectual property rights of others.</li>
              <li>Distribute malware or attempt to compromise our systems.</li>
              <li>Scrape, crawl, or systematically access our Service through automated means without written permission.</li>
              <li>Resell or commercially redistribute generated business plans as a competing service.</li>
            </ul>
          </section>

          {/* 15 */}
          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-3">15. Termination</h2>
            <p>
              We reserve the right to refuse service, terminate access, or cancel orders at our sole discretion,
              without prior notice, for any reason including but not limited to violation of these Terms or suspected
              fraudulent activity. In the event of termination for cause, no refund will be issued.
            </p>
          </section>

          {/* 16 */}
          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-3">16. Governing Law and Dispute Resolution</h2>
            <p>
              These Terms shall be governed by and construed in accordance with the laws of the State of Delaware,
              United States, without regard to its conflict of law provisions.
            </p>
            <p className="mt-3">
              Any dispute arising out of or relating to these Terms or the Service shall first be attempted to be
              resolved through good-faith negotiation. If the dispute cannot be resolved within 30 days of written
              notice, it shall be resolved through binding arbitration administered in accordance with the rules of
              the American Arbitration Association. The arbitration shall be conducted in English, and the
              arbitrator&rsquo;s decision shall be final and binding.
            </p>
            <p className="mt-3">
              You agree to waive any right to participate in a class action lawsuit or class-wide arbitration against
              BizPlan Genius.
            </p>
          </section>

          {/* 17 */}
          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-3">17. Severability</h2>
            <p>
              If any provision of these Terms is found to be unenforceable or invalid by a court of competent
              jurisdiction, that provision shall be limited or eliminated to the minimum extent necessary so that
              these Terms shall otherwise remain in full force and effect.
            </p>
          </section>

          {/* 18 */}
          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-3">18. Entire Agreement</h2>
            <p>
              These Terms, together with our Privacy Policy, constitute the entire agreement between you and BizPlan
              Genius regarding the use of the Service and supersede all prior agreements, understandings, and
              communications, whether written or oral.
            </p>
          </section>

          {/* 19 */}
          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-3">19. Contact Us</h2>
            <p>
              If you have any questions about these Terms, please contact us at:{' '}
              <a href="mailto:support@bizplangenius.com" className="text-blue-600 hover:text-blue-800 underline">
                support@bizplangenius.com
              </a>
            </p>
          </section>

        </div>
      </main>

      {/* Footer */}
      <footer className="border-t border-gray-100 mt-16">
        <div className="max-w-4xl mx-auto px-4 py-8 flex flex-col sm:flex-row items-center justify-between gap-4 text-sm text-gray-500">
          <p>&copy; 2026 BizPlan Genius. All rights reserved.</p>
          <div className="flex gap-6">
            <Link href="/privacy" className="hover:text-gray-700 transition">Privacy Policy</Link>
            <Link href="/terms" className="hover:text-gray-700 transition font-medium text-gray-700">Terms of Service</Link>
            <a href="mailto:support@bizplangenius.com" className="hover:text-gray-700 transition">Contact</a>
          </div>
        </div>
      </footer>
    </div>
  );
}
