import UpsellModule from '@/app/components/UpsellModule';
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'E-2 Visa Business Plan: USCIS-Ready Template in Minutes for $147 | BizPlan Genius',
  description:
    'Skip the $2,000 to $5,000 immigration consultant. Generate a complete E-2, L-1, or EB-5 visa business plan with 5-year financials, market analysis, and job-creation projections. Ready in 10 minutes. $147 one-time, money-back guarantee.',
  keywords:
    'E-2 visa business plan, L-1 visa business plan, EB-5 business plan, treaty investor business plan, USCIS business plan, immigration business plan, E-2 visa business plan template, E-2 visa business plan example, business plan for E-2 visa',
  alternates: {
    canonical: '/e2-visa-business-plan',
  },
  openGraph: {
    title: 'E-2 Visa Business Plan: USCIS-Ready in 10 Minutes',
    description:
      'Complete E-2, L-1, or EB-5 visa business plan. 5-year financials, market analysis, job creation. Cheaper than a consultant. Money-back guarantee.',
    url: 'https://www.bizplangenius.com/e2-visa-business-plan',
    siteName: 'BizPlan Genius',
    type: 'website',
    images: [
      {
        url: '/api/og?title=E-2+Visa+Business+Plan&subtitle=USCIS-ready+plan+with+5-year+financials.+%24147+one-time.+Cheaper+than+a+consultant.&badge=Visa+Plan',
        width: 1200,
        height: 630,
        alt: 'BizPlan Genius - E-2 Visa Business Plan for $147',
      },
    ],
  },
  twitter: {
    card: 'summary_large_image',
    title: 'E-2 Visa Business Plan in 10 Minutes - $147',
    description: 'USCIS-ready plan with 5-year financials and market analysis. Money-back guarantee.',
    images: ['/api/og?title=E-2+Visa+Business+Plan&subtitle=USCIS-ready+plan+with+5-year+financials.+%24147+one-time.&badge=Visa+Plan'],
  },
};

export default function E2VisaLayout({ children }: { children: React.ReactNode }) {
  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{
          __html: JSON.stringify({
            '@context': 'https://schema.org',
            '@type': 'Product',
            name: 'E-2 Visa Business Plan',
            description:
              'AI-generated E-2, L-1, or EB-5 visa business plan with 5-year financial projections, market analysis, and job creation forecast. Designed as a starting point for your immigration attorney.',
            url: 'https://www.bizplangenius.com/e2-visa-business-plan',
            brand: { '@type': 'Brand', name: 'BizPlan Genius' },
            offers: {
              '@type': 'Offer',
              price: '147.00',
              priceCurrency: 'USD',
              availability: 'https://schema.org/InStock',
              priceValidUntil: '2026-12-31',
              url: 'https://www.bizplangenius.com/e2-visa-business-plan',
            },
          }),
        }}
      />
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{
          __html: JSON.stringify({
            '@context': 'https://schema.org',
            '@type': 'FAQPage',
            mainEntity: [
              {
                '@type': 'Question',
                name: 'Will USCIS accept a business plan generated by AI?',
                acceptedAnswer: {
                  '@type': 'Answer',
                  text: 'Our plan is designed as a strong starting point for your immigration attorney to review and refine for your specific case. USCIS evaluates the business itself, not how the plan was drafted. Most attorneys use a template like this as the base and add case-specific narrative. We are not immigration counsel.',
                },
              },
              {
                '@type': 'Question',
                name: 'What is included in the E-2 visa business plan?',
                acceptedAnswer: {
                  '@type': 'Answer',
                  text: 'Executive summary, business description, market and industry analysis with real competitor research, 5-year financial projections, staffing and job-creation plan, marketing and sales strategy, operations plan, and risk analysis. Delivered as a professional PDF.',
                },
              },
              {
                '@type': 'Question',
                name: 'How is this different from a $2,000 to $5,000 immigration consultant?',
                acceptedAnswer: {
                  '@type': 'Answer',
                  text: 'Specialty E-2 plan writers charge $1,500 to $5,000 and take two to four weeks. We deliver a professionally structured plan in under 10 minutes for $147. For complex EB-5 cases involving regional centers, you may still want a specialist. For straightforward E-2 and L-1 filings, our plan plus your attorney is usually enough.',
                },
              },
              {
                '@type': 'Question',
                name: 'Does the plan include 5-year financials?',
                acceptedAnswer: {
                  '@type': 'Answer',
                  text: 'Yes. Our Pro plan includes 5-year revenue projections, expense forecasts, hiring schedule, and job creation timeline, the financial elements USCIS officers most commonly look for in E-2 and L-1 petitions.',
                },
              },
              {
                '@type': 'Question',
                name: 'What if the plan is not good enough?',
                acceptedAnswer: {
                  '@type': 'Answer',
                  text: 'Pro plan includes a 100% money-back guarantee. If your immigration attorney rejects the plan as a starting point, request a full refund within 14 days.',
                },
              },
            ],
          }),
        }}
      />
      {children}
      <UpsellModule />
    </>
  );
}
