import Link from 'next/link';
import type { Metadata } from 'next';

export default function E2VisaBusinessPlanPage() {
  const sections = [
    'Executive Summary tailored to E-2 / L-1 / EB-5 evaluation criteria',
    'Business Description with treaty country, ownership structure, and capital narrative',
    'Market and Industry Analysis with real competitor research (Gemini + live web search)',
    '5-Year Financial Projections: revenue, expenses, cash flow, balance sheet',
    'Job Creation and Staffing Plan with 5-year hiring schedule',
    'Marketing and Sales Strategy with go-to-market detail',
    'Operations Plan with location, suppliers, and milestone roadmap',
    'Risk Analysis and Mitigation Strategies',
    'Investment Source and Use of Funds breakdown',
    'Professional PDF (30-50 pages, attorney-friendly format)',
  ];

  const stats = [
    { value: '$147', label: 'One-time price' },
    { value: '10 min', label: 'Delivery time' },
    { value: 'USCIS', label: 'Format-aligned' },
  ];

  const faqs = [
    {
      q: 'Will USCIS accept a business plan generated by AI?',
      a: 'USCIS evaluates the underlying business, not how the plan was drafted. Our plan is structured as a strong starting point your immigration attorney can refine and submit. We are not immigration counsel. We do not file petitions. Always have your attorney review the final plan before submission.',
    },
    {
      q: 'How is this different from a $2,000 to $5,000 specialty plan writer?',
      a: 'Specialty E-2 plan consultants charge $1,500 to $5,000 and typically take two to four weeks. We deliver a professionally structured plan in under 10 minutes for $147. For complex EB-5 regional center cases, a specialist may still be needed. For straightforward E-2, L-1, and direct EB-5 filings, our plan plus your attorney is usually enough.',
    },
    {
      q: 'Does the plan include 5-year financials and a job creation forecast?',
      a: 'Yes. The Pro plan and Full Business Kit both include 5-year revenue projections, expense forecasts, hiring schedule, and a job creation timeline.',
    },
    {
      q: 'I am applying for an E-2 from the UK / India / Mexico / Turkey / Pakistan / Australia. Will the plan work?',
      a: 'Yes. The plan is structured around USCIS criteria, which are country-agnostic. The treaty country narrative is generated based on your input. We have customers applying from most E-2 treaty countries.',
    },
    {
      q: 'Can I use this for an L-1A new office petition?',
      a: 'Yes. L-1A new office petitions require a one-year staffing and revenue plan plus three to five-year projections, all of which are included.',
    },
    {
      q: 'What if my immigration attorney rejects the plan?',
      a: 'Full refund within 14 days under our money-back guarantee on the Pro plan. We want this to be useful to your attorney, not extra paperwork.',
    },
    {
      q: 'How much investment capital do I need to qualify for an E-2?',
      a: 'USCIS does not set a minimum, but in practice most approved E-2 petitions involve at least $80,000 to $200,000 of substantial, at-risk investment. Our plan helps you document the investment narrative; it does not guarantee approval.',
    },
    {
      q: 'Do I need to be in the US to use this?',
      a: 'No. You can purchase, generate, and download from anywhere in the world.',
    },
  ];

  return (
    <div className="min-h-screen bg-white">
      <header className="border-b">
        <div className="max-w-5xl mx-auto px-6 py-4 flex items-center justify-between">
          <Link href="/" className="text-xl font-bold text-gray-900">BizPlan Genius</Link>
          <Link href="/generate?tier=pro&purpose=visa" className="text-sm font-medium bg-blue-600 text-white px-4 py-2 rounded-lg hover:bg-blue-700">
            Get My E-2 Plan - $147
          </Link>
        </div>
      </header>

      <main className="max-w-4xl mx-auto px-6 py-16">
        <div className="text-center mb-12">
          <div className="inline-block px-4 py-1.5 bg-blue-50 text-blue-700 text-sm font-medium rounded-full mb-6 border border-blue-100">
            For E-2, L-1, and EB-5 visa applicants
          </div>
          <h1 className="text-3xl sm:text-5xl font-extrabold text-gray-900 mb-4 leading-tight">
            E-2 Visa Business Plan in 10 Minutes
          </h1>
          <p className="text-lg sm:text-xl text-gray-600 max-w-2xl mx-auto mb-3">
            Skip the $2,000 to $5,000 specialty consultant. Get a USCIS-aligned business plan with 5-year financials, real market analysis, and a complete job creation forecast for $147.
          </p>
          <p className="text-base text-gray-500 max-w-2xl mx-auto mb-8">
            Designed to give your immigration attorney a strong starting point. Money-back guarantee.
          </p>
          <div className="flex flex-col sm:flex-row gap-3 justify-center">
            <Link href="/generate?tier=pro&purpose=visa" className="px-8 py-3 bg-blue-600 text-white font-bold rounded-lg hover:bg-blue-700 transition shadow-lg shadow-blue-600/20">
              Generate My E-2 Plan - $147
            </Link>
            <Link href="/bundles" className="px-8 py-3 border-2 border-gray-200 text-gray-700 font-semibold rounded-lg hover:border-blue-300 transition">
              See Full Business Kit - $447
            </Link>
          </div>
          <p className="mt-4 text-xs text-gray-400">
            One-time payment. No subscription. Money-back guarantee on Pro and Full Kit.
          </p>
        </div>

        <div className="grid grid-cols-3 gap-4 mb-12">
          {stats.map((s, i) => (
            <div key={i} className="text-center p-4 bg-gray-50 rounded-xl">
              <p className="text-xl sm:text-2xl font-extrabold text-blue-600">{s.value}</p>
              <p className="text-xs text-gray-500 mt-1">{s.label}</p>
            </div>
          ))}
        </div>

        <div className="bg-amber-50 border border-amber-200 rounded-2xl p-6 mb-12 text-sm text-amber-900">
          <p className="font-semibold mb-1">Important: read this before you buy.</p>
          <p>BizPlan Genius is not a law firm or immigration consultancy. We do not file petitions, give legal advice, or guarantee USCIS approval. We generate professionally structured business plans that your immigration attorney can use as a starting point. USCIS approval depends on your specific case, your attorney&apos;s work, and the merits of your business.</p>
        </div>

        <div className="bg-gray-50 rounded-2xl p-8 mb-12">
          <h2 className="text-2xl font-bold text-gray-900 mb-2">What is in your E-2 visa business plan</h2>
          <p className="text-sm text-gray-500 mb-6">Pro plan, $147. Full Business Kit at $447 adds logo, website, pitch deck, and legal pages.</p>
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
            {sections.map((s, i) => (
              <div key={i} className="flex items-start gap-3">
                <svg className="w-5 h-5 text-green-500 flex-shrink-0 mt-0.5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2.5} d="M5 13l4 4L19 7" />
                </svg>
                <span className="text-gray-700">{s}</span>
              </div>
            ))}
          </div>
        </div>

        <div className="mb-12">
          <h2 className="text-2xl font-bold text-gray-900 mb-6 text-center">Why founders applying for E-2 use us</h2>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
            <div className="bg-white border rounded-xl p-6">
              <p className="font-bold text-gray-900 mb-2">Cost</p>
              <p className="text-sm text-gray-600">Specialty consultants charge $1,500 to $5,000. Our plan is $147 with the same core structure your attorney expects to see.</p>
            </div>
            <div className="bg-white border rounded-xl p-6">
              <p className="font-bold text-gray-900 mb-2">Speed</p>
              <p className="text-sm text-gray-600">Consultants take two to four weeks. Filing deadlines do not wait. We deliver in 10 minutes.</p>
            </div>
            <div className="bg-white border rounded-xl p-6">
              <p className="font-bold text-gray-900 mb-2">Real data</p>
              <p className="text-sm text-gray-600">Powered by Google Gemini 2.5 with live web grounding. Real competitor pricing, real market data, not generic AI filler.</p>
            </div>
          </div>
        </div>

        <div className="mb-12">
          <h2 className="text-2xl font-bold text-gray-900 mb-6 text-center">How it works</h2>
          <div className="grid grid-cols-1 sm:grid-cols-3 gap-6">
            {[
              { step: '1', title: 'Tell us about your business', desc: 'Treaty country, capital, location, industry, target market. 3 minutes.' },
              { step: '2', title: 'AI builds your plan', desc: 'Real competitor research, 5-year financials, job creation forecast. 5 minutes.' },
              { step: '3', title: 'Hand to your attorney', desc: 'Download your PDF. Send to immigration counsel for review and submission.' },
            ].map((s, i) => (
              <div key={i} className="text-center">
                <div className="w-10 h-10 bg-blue-100 rounded-full flex items-center justify-center mx-auto mb-3 text-blue-600 font-bold">{s.step}</div>
                <p className="font-bold text-gray-900 mb-1">{s.title}</p>
                <p className="text-sm text-gray-500">{s.desc}</p>
              </div>
            ))}
          </div>
        </div>

        <div className="mb-12">
          <h2 className="text-2xl font-bold text-gray-900 mb-6 text-center">Frequently asked questions</h2>
          <div className="space-y-4">
            {faqs.map((f, i) => (
              <div key={i} className="border rounded-xl p-5">
                <p className="font-semibold text-gray-900 mb-2">{f.q}</p>
                <p className="text-sm text-gray-600">{f.a}</p>
              </div>
            ))}
          </div>
        </div>

        <div className="bg-blue-600 rounded-2xl p-8 text-center text-white mb-12">
          <h2 className="text-2xl font-bold mb-3">Ready to build your E-2, L-1, or EB-5 plan?</h2>
          <p className="text-blue-100 mb-6">10 minutes. $147. Your immigration attorney will thank you.</p>
          <div className="flex flex-col sm:flex-row gap-3 justify-center">
            <Link href="/generate?tier=pro&purpose=visa" className="inline-block bg-white text-blue-600 px-8 py-3 rounded-lg font-bold hover:bg-blue-50 transition">
              Generate My Plan - $147
            </Link>
            <Link href="/bundles" className="inline-block border-2 border-white text-white px-8 py-3 rounded-lg font-bold hover:bg-blue-700 transition">
              Full Business Kit - $447
            </Link>
          </div>
        </div>

        <div className="text-center text-sm text-gray-500">
          <p className="mb-2">Related resources:</p>
          <div className="flex flex-wrap justify-center gap-4">
            <Link href="/sba-loan-business-plan" className="text-blue-600 hover:underline">SBA Loan Business Plan</Link>
            <Link href="/spy" className="text-blue-600 hover:underline">Competitor Analysis</Link>
            <Link href="/pitch-deck" className="text-blue-600 hover:underline">Pitch Deck</Link>
            <Link href="/build-website" className="text-blue-600 hover:underline">Auto-Website Builder</Link>
          </div>
        </div>
      </main>
    </div>
  );
}
